mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.c4.hero.domain.**.dto

spring:
  config:
    import: optional:classpath:application-secret.yml

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

