spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**/ApprovalMapper.xml
  type-aliases-package: com.c4.hero.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl